import type { VowelContrastContent } from "./vowel-contrast-types";

export const SHORT_I_LONG_I: VowelContrastContent = {
  vowel: "i",
  title: "I Sounds",
  emoji: "🪁",
  nameRuleTip:
    "In Short I words, I makes a quick 'ih' sound. In Long I words, I wants to be famous and says its own name: 'Iii!'",
  magicEIntro: "The silent E is like a magic wand — zap the word and I says its name!",
  vowelTeamIntro:
    "Sometimes Y, IGH, or other letters team up to make the Long I sound — they don't always look alike!",
  vowelTeamNote: "These pairs sound different — that's okay! The goal is hearing Short I (ih) vs Long I (Iii).",
  shortLabel: "Short I",
  shortSound: "ih",
  shortEmoji: "🐷",
  longLabel: "Long I",
  longSound: "Iii",
  longClipKey: "eye",
  longEmoji: "🧊",
  stretchIntro: "Short I is a quick squeak. Long I is a big smile stretch!",
  stretchShortCue: "Ih-ih-ih!",
  stretchLongCue: "Iiiiiii",
  storyHint: 'Read "The Kite in the Sky" to hear Long I in a story!',
  magicEPairs: [
    { pattern: "magic-e", short: { word: "fin", meaning: "on a fish" }, long: { word: "fine", meaning: "doing well" } },
    { pattern: "magic-e", short: { word: "kit", meaning: "a small set" }, long: { word: "kite", meaning: "flies in wind" } },
    { pattern: "magic-e", short: { word: "bit", meaning: "a tiny piece" }, long: { word: "bite", meaning: "with your teeth" } },
    { pattern: "magic-e", short: { word: "rid", meaning: "to get rid of" }, long: { word: "ride", meaning: "on a bike" } },
    { pattern: "magic-e", short: { word: "dim", meaning: "not bright" }, long: { word: "dime", meaning: "the coin" } },
    { pattern: "magic-e", short: { word: "win", meaning: "come first" }, long: { word: "line", meaning: "a row" } },
  ],
  vowelTeamPairs: [
    { pattern: "vowel-team", short: { word: "fill", meaning: "to pour in" }, long: { word: "fly", meaning: "in the sky" } },
    { pattern: "vowel-team", short: { word: "sick", meaning: "not feeling well" }, long: { word: "high", meaning: "up above" } },
    { pattern: "vowel-team", short: { word: "hill", meaning: "a small mountain" }, long: { word: "light", meaning: "from the sun" } },
    { pattern: "vowel-team", short: { word: "spin", meaning: "to turn around" }, long: { word: "sky", meaning: "above us" } },
  ],
  soundSortWords: [
    { word: "pig", sound: "short" },
    { word: "kite", sound: "long" },
    { word: "bin", sound: "short" },
    { word: "ride", sound: "long" },
    { word: "sit", sound: "short" },
    { word: "light", sound: "long" },
    { word: "fin", sound: "short" },
    { word: "fine", sound: "long" },
    { word: "kit", sound: "short" },
    { word: "bit", sound: "short" },
    { word: "bite", sound: "long" },
    { word: "dim", sound: "short" },
    { word: "dime", sound: "long" },
    { word: "hill", sound: "short" },
    { word: "sky", sound: "long" },
    { word: "fly", sound: "long" },
  ],
  stretchPairs: [
    { pattern: "magic-e", short: { word: "fin", meaning: "on a fish" }, long: { word: "fine", meaning: "doing well" } },
    { pattern: "magic-e", short: { word: "kit", meaning: "a small set" }, long: { word: "kite", meaning: "flies in wind" } },
    { pattern: "magic-e", short: { word: "bit", meaning: "a tiny piece" }, long: { word: "bite", meaning: "with your teeth" } },
    { pattern: "magic-e", short: { word: "rid", meaning: "to get rid of" }, long: { word: "ride", meaning: "on a bike" } },
  ],
};
