/** Word → phonics chunk map for reading fundamentals */
export const PHONICS_MAP: Record<string, string[]> = {
  // Level 1 — CVC
  CAT: ["C", "A", "T"],
  DOG: ["D", "O", "G"],
  PIG: ["P", "I", "G"],
  BUG: ["B", "U", "G"],
  SUN: ["S", "U", "N"],
  BAT: ["B", "A", "T"],
  HAT: ["H", "A", "T"],
  BOX: ["B", "O", "X"],
  FOX: ["F", "O", "X"],
  MUG: ["M", "U", "G"],
  LOG: ["L", "O", "G"],
  RAT: ["R", "A", "T"],
  CUP: ["C", "U", "P"],
  FIX: ["F", "I", "X"],
  LID: ["L", "I", "D"],
  MUD: ["M", "U", "D"],
  NET: ["N", "E", "T"],
  NUT: ["N", "U", "T"],
  ROD: ["R", "O", "D"],
  TUB: ["T", "U", "B"],
  // Level 2 — 4-letter
  FISH: ["F", "I", "SH"],
  DUCK: ["D", "U", "CK"],
  FROG: ["FR", "O", "G"],
  BIRD: ["B", "IR", "D"],
  TREE: ["TR", "EE"],
  BOOK: ["B", "OO", "K"],
  BALL: ["B", "A", "LL"],
  BEAR: ["B", "EA", "R"],
  BOAT: ["B", "OA", "T"],
  MOON: ["M", "OO", "N"],
  STAR: ["ST", "A", "R"],
  CAKE: ["C", "A", "KE"],
  BANK: ["B", "AN", "K"],
  BASE: ["B", "A", "SE"],
  CAMP: ["C", "A", "MP"],
  CASH: ["C", "A", "SH"],
  CAVE: ["C", "A", "VE"],
  COIN: ["C", "OI", "N"],
  DART: ["D", "AR", "T"],
  HIKE: ["H", "I", "KE"],
  PARK: ["P", "AR", "K"],
  PLAY: ["PL", "A", "Y"],
  RIDE: ["R", "I", "DE"],
  ROCK: ["R", "O", "CK"],
  SAVE: ["S", "A", "VE"],
  SHIP: ["SH", "I", "P"],
  TENT: ["T", "E", "NT"],
  TOOL: ["T", "OO", "L"],
  CAP: ["C", "A", "P"],
  CAPE: ["C", "A", "PE"],
  CANE: ["C", "A", "NE"],
  MAD: ["M", "A", "D"],
  MADE: ["M", "A", "DE"],
  TAPE: ["T", "A", "PE"],
  RATE: ["R", "A", "TE"],
  PLAN: ["P", "L", "AN"],
  PLANE: ["P", "L", "ANE"],
  BACK: ["B", "A", "CK"],
  MAN: ["M", "A", "N"],
  PAN: ["P", "A", "N"],
  MAIN: ["M", "AI", "N"],
  PAIN: ["P", "AI", "N"],
  PAY: ["P", "AY"],
  BAY: ["B", "AY"],
  MAID: ["M", "AI", "D"],
  LAKE: ["L", "A", "KE"],
  BAKE: ["B", "A", "KE"],
  MATE: ["M", "A", "TE"],
  GATE: ["G", "A", "TE"],
  WANTS: ["W", "A", "NTS"],
  SEES: ["S", "EE", "S"],
  BUT: ["B", "UT"],
  HE: ["HE"],
  BY: ["B", "Y"],
  FOR: ["F", "OR"],
  HIS: ["H", "IS"],
  // Level 3 — 5-letter
  HOUSE: ["H", "OU", "SE"],
  APPLE: ["A", "PP", "LE"],
  TRAIN: ["TR", "AI", "N"],
  HORSE: ["H", "OR", "SE"],
  MOUSE: ["M", "OU", "SE"],
  CHAIR: ["CH", "AI", "R"],
  CLOUD: ["CL", "OU", "D"],
  SHEEP: ["SH", "EE", "P"],
  SNAKE: ["SN", "A", "KE"],
  TIGER: ["T", "I", "GER"],
  GRASS: ["GR", "A", "SS"],
  TRUCK: ["TR", "U", "CK"],
  ALIEN: ["A", "LI", "EN"],
  BEACH: ["B", "EA", "CH"],
  BOARD: ["B", "OA", "RD"],
  BRUSH: ["BR", "U", "SH"],
  CABIN: ["C", "AB", "IN"],
  CATCH: ["C", "A", "TCH"],
  DRILL: ["DR", "I", "LL"],
  FIELD: ["F", "IE", "LD"],
  GLOVE: ["GL", "O", "VE"],
  MAGIC: ["M", "A", "GIC"],
  MONEY: ["M", "O", "NEY"],
  OCEAN: ["O", "CE", "AN"],
  RIVER: ["R", "I", "VER"],
  SHELL: ["SH", "EL", "L"],
  SMILE: ["SM", "I", "LE"],
  THROW: ["TH", "R", "OW"],
  TRAIL: ["TR", "AI", "L"],
  WATER: ["W", "A", "TER"],
  // Level 4 — 6-7 letter
  FLOWER: ["FL", "OW", "ER"],
  RABBIT: ["R", "AB", "BIT"],
  MONKEY: ["M", "ON", "KEY"],
  SPIDER: ["SP", "I", "DER"],
  PENCIL: ["P", "EN", "CIL"],
  ORANGE: ["OR", "AN", "GE"],
  DRAGON: ["DR", "A", "GON"],
  TURTLE: ["T", "UR", "TLE"],
  LIZARD: ["L", "IZ", "ARD"],
  CASTLE: ["C", "AS", "TLE"],
  ROCKET: ["R", "O", "CKET"],
  DOCTOR: ["D", "OC", "TOR"],
  ANIMAL: ["AN", "I", "MAL"],
  BATTER: ["B", "AT", "TER"],
  BUCKET: ["B", "U", "CK", "ET"],
  CAMERA: ["C", "AM", "ER", "A"],
  CANYON: ["CAN", "Y", "ON"],
  DOLLAR: ["D", "OL", "LAR"],
  FLIGHT: ["FL", "IGH", "T"],
  FOREST: ["FOR", "E", "ST"],
  GALAXY: ["GAL", "AX", "Y"],
  HAMMER: ["H", "AM", "MER"],
  HIKING: ["H", "I", "KING"],
  ISLAND: ["IS", "L", "AND"],
  NATURE: ["N", "A", "TURE"],
  PARADE: ["PA", "R", "ADE"],
  PITCHER: ["P", "I", "TCH", "ER"],
  PLANET: ["PL", "AN", "ET"],
  TICKET: ["T", "I", "CK", "ET"],
  WALLEYE: ["WALL", "EYE"],
  // Level 5 — 8+ letter
  ELEPHANT: ["EL", "E", "PHANT"],
  DINOSAUR: ["D", "I", "NO", "SAUR"],
  BUTTERFLY: ["B", "UT", "TER", "FLY"],
  MOUNTAIN: ["M", "OUN", "TAIN"],
  UMBRELLA: ["UM", "BR", "ELLA"],
  AIRPLANE: ["AIR", "PL", "ANE"],
  ASTRONAUT: ["AS", "TRO", "NAUT"],
  HELICOPTER: ["HEL", "I", "COP", "TER"],
  KANGAROO: ["KAN", "GA", "ROO"],
  ALLIGATOR: ["AL", "LI", "GA", "TOR"],
  VOLCANO: ["VOL", "CA", "NO"],
  TELESCOPE: ["TEL", "E", "SCOPE"],
  ADVENTURE: ["AD", "VEN", "TURE"],
  BACKPACK: ["BACK", "P", "ACK"],
  BASEBALL: ["BASE", "B", "ALL"],
  BLEACHERS: ["BLEACH", "ERS"],
  CAMPFIRE: ["CAMP", "F", "IRE"],
  CAMPGROUND: ["CAMP", "GROUND"],
  MINNESOTA: ["MIN", "NE", "SO", "TA"],
  MOSQUITO: ["MOS", "QUI", "TO"],
  PRINCESS: ["PRIN", "C", "ESS"],
  ROADTRIP: ["ROAD", "TRIP"],
  SPACESHIP: ["SPACE", "SH", "IP"],
  SUNGLASSES: ["SUN", "GL", "ASS", "ES"],
  SUNSHINE: ["SUN", "SH", "INE"],
  THEMEPARK: ["THEME", "P", "ARK"],
  VACATION: ["VA", "CA", "TION"],
  WATERFALL: ["WAT", "ER", "FALL"],
  WILDERNESS: ["WILD", "ER", "NESS"],
  WOODLAND: ["WOOD", "L", "AND"],
  // Sight words used in sentences and books
  THE: ["TH", "E"],
  A: ["A"],
  AN: ["A", "N"],
  I: ["I"],
  IS: ["I", "S"],
  IT: ["I", "T"],
  ON: ["O", "N"],
  AT: ["A", "T"],
  LAD: ["L", "A", "D"],
  BAG: ["B", "A", "G"],
  VAN: ["V", "A", "N"],
  NAP: ["N", "A", "P"],
  TAP: ["T", "A", "P"],
  HAD: ["H", "A", "D"],
  TAG: ["T", "A", "G"],
  CAN: ["C", "A", "N"],
  HAS: ["H", "A", "S"],
  IN: ["I", "N"],
  MY: ["M", "Y"],
  WE: ["W", "E"],
  TO: ["T", "O"],
  GO: ["G", "O"],
  SIT: ["S", "I", "T"],
  BIN: ["B", "I", "N"],
  WITH: ["W", "I", "TH"],
  SEE: ["S", "EE"],
  SAT: ["S", "A", "T"],
  HOT: ["H", "O", "T"],
  HOP: ["H", "O", "P"],
  DID: ["D", "I", "D"],
  BIG: ["B", "I", "G"],
  RED: ["R", "E", "D"],
  HEN: ["H", "E", "N"],
  PEN: ["P", "E", "N"],
  BED: ["B", "E", "D"],
  FED: ["F", "E", "D"],
  TEN: ["T", "E", "N"],
  HENS: ["H", "E", "N", "S"],
  BUS: ["B", "U", "S"],
  FLY: ["F", "L", "Y"],
  FIN: ["F", "I", "N"],
  FINE: ["F", "I", "NE"],
  KIT: ["K", "I", "T"],
  KITE: ["K", "I", "TE"],
  BIT: ["B", "I", "T"],
  BITE: ["B", "I", "TE"],
  RID: ["R", "I", "D"],
  DIM: ["D", "I", "M"],
  DIME: ["D", "I", "ME"],
  LINE: ["L", "I", "NE"],
  WIN: ["W", "I", "N"],
  FILL: ["F", "I", "LL"],
  SICK: ["S", "I", "CK"],
  HILL: ["H", "I", "LL"],
  SPIN: ["SP", "I", "N"],
  HIGH: ["H", "IGH"],
  LIGHT: ["L", "IGH", "T"],
  SKY: ["SK", "Y"],
  ICE: ["I", "CE"],
  BIKE: ["B", "I", "KE"],
  WHITE: ["WH", "I", "TE"],
  SIGHT: ["S", "IGH", "T"],
  NIGHT: ["N", "IGH", "T"],
  FUN: ["F", "U", "N"],
  FLIES: ["FL", "IES"],
  LOOK: ["L", "OO", "K"],
  LIKE: ["L", "I", "KE"],
  LOVE: ["L", "O", "VE"],
  MOM: ["M", "O", "M"],
  BRIGHT: ["BR", "I", "GHT"],
  HAPPY: ["H", "AP", "PY"],
  KID: ["K", "I", "D"],
  PLAYS: ["PL", "A", "YS"],
  HAVE: ["H", "A", "VE"],
  READ: ["R", "EA", "D"],
  MAT: ["M", "A", "T"],
  RUN: ["R", "U", "N"],
  RAN: ["R", "A", "N"],
  FAT: ["F", "A", "T"],
  SAW: ["S", "AW"],
  SWIM: ["SW", "I", "M"],
  HID: ["H", "I", "D"],
  JUMP: ["J", "U", "MP"],
  SCHOOL: ["SCH", "OO", "L"],
  SHE: ["SH", "E"],
  WILL: ["W", "ILL"],
  OVER: ["O", "VER"],
  FAST: ["F", "A", "ST"],
  REAL: ["R", "EA", "L"],
  USE: ["U", "SE"],
  GREEN: ["GR", "EE", "N"],
  SAND: ["S", "A", "ND"],
  WOODS: ["W", "OO", "DS"],
  STARS: ["ST", "AR", "S"],
  HIT: ["H", "I", "T"],
  TODAY: ["TO", "D", "AY"],
  BROWN: ["BR", "OW", "N"],
};

export function getPhonicsForWord(word: string): string[] {
  const upper = word.toUpperCase().replace(/[^A-Z]/g, "");
  if (!upper) return [];
  if (PHONICS_MAP[upper]) return PHONICS_MAP[upper];
  return upper.split("");
}

export function getPhonicsForSentence(sentence: string): Map<string, string[]> {
  const map = new Map<string, string[]>();
  for (const raw of sentence.split(/\s+/)) {
    const word = raw.replace(/[^A-Za-z]/g, "");
    if (word && !map.has(word.toUpperCase())) {
      map.set(word.toUpperCase(), getPhonicsForWord(word));
    }
  }
  return map;
}
