/** Word → phonics chunk map for reading fundamentals */
export const PHONICS_MAP: Record<string, string[]> = {
  // Level 1 — CVC
  CAT: ["C", "A", "T"],
  DOG: ["D", "O", "G"],
  PIG: ["P", "I", "G"],
  BUG: ["B", "U", "G"],
  SUN: ["S", "U", "N"],
  BAT: ["B", "A", "T"],
  HAT: ["H", "A", "T"],
  BOX: ["B", "O", "X"],
  FOX: ["F", "O", "X"],
  MUG: ["M", "U", "G"],
  LOG: ["L", "O", "G"],
  RAT: ["R", "A", "T"],
  // Level 2 — 4-letter
  FISH: ["F", "I", "SH"],
  DUCK: ["D", "U", "CK"],
  FROG: ["FR", "O", "G"],
  BIRD: ["B", "IR", "D"],
  TREE: ["TR", "EE"],
  BOOK: ["B", "OO", "K"],
  BALL: ["B", "A", "LL"],
  BEAR: ["B", "EA", "R"],
  BOAT: ["B", "OA", "T"],
  MOON: ["M", "OO", "N"],
  STAR: ["ST", "A", "R"],
  CAKE: ["C", "A", "KE"],
  CAP: ["C", "A", "P"],
  CAPE: ["C", "A", "PE"],
  CANE: ["C", "A", "NE"],
  MAD: ["M", "A", "D"],
  MADE: ["M", "A", "DE"],
  TAPE: ["T", "A", "PE"],
  RATE: ["R", "A", "TE"],
  PLAN: ["P", "L", "AN"],
  PLANE: ["P", "L", "ANE"],
  BACK: ["B", "A", "CK"],
  MAN: ["M", "A", "N"],
  PAN: ["P", "A", "N"],
  MAIN: ["M", "AI", "N"],
  PAIN: ["P", "AI", "N"],
  PAY: ["P", "AY"],
  BAY: ["B", "AY"],
  MAID: ["M", "AI", "D"],
  LAKE: ["L", "A", "KE"],
  BAKE: ["B", "A", "KE"],
  MATE: ["M", "A", "TE"],
  GATE: ["G", "A", "TE"],
  WANTS: ["W", "A", "NTS"],
  SEES: ["S", "EE", "S"],
  BUT: ["B", "UT"],
  HE: ["HE"],
  BY: ["B", "Y"],
  FOR: ["F", "OR"],
  HIS: ["H", "IS"],
  // Level 3 — 5-letter
  HOUSE: ["H", "OU", "SE"],
  APPLE: ["A", "PP", "LE"],
  TRAIN: ["TR", "AI", "N"],
  HORSE: ["H", "OR", "SE"],
  MOUSE: ["M", "OU", "SE"],
  CHAIR: ["CH", "AI", "R"],
  CLOUD: ["CL", "OU", "D"],
  SHEEP: ["SH", "EE", "P"],
  SNAKE: ["SN", "A", "KE"],
  TIGER: ["T", "I", "GER"],
  GRASS: ["GR", "A", "SS"],
  TRUCK: ["TR", "U", "CK"],
  // Level 4 — 6-7 letter
  FLOWER: ["FL", "OW", "ER"],
  RABBIT: ["R", "AB", "BIT"],
  MONKEY: ["M", "ON", "KEY"],
  SPIDER: ["SP", "I", "DER"],
  PENCIL: ["P", "EN", "CIL"],
  ORANGE: ["OR", "AN", "GE"],
  DRAGON: ["DR", "A", "GON"],
  TURTLE: ["T", "UR", "TLE"],
  LIZARD: ["L", "IZ", "ARD"],
  CASTLE: ["C", "AS", "TLE"],
  ROCKET: ["R", "O", "CKET"],
  DOCTOR: ["D", "OC", "TOR"],
  // Level 5 — 8+ letter
  ELEPHANT: ["EL", "E", "PHANT"],
  DINOSAUR: ["D", "I", "NO", "SAUR"],
  BUTTERFLY: ["B", "UT", "TER", "FLY"],
  MOUNTAIN: ["M", "OUN", "TAIN"],
  UMBRELLA: ["UM", "BR", "ELLA"],
  AIRPLANE: ["AIR", "PL", "ANE"],
  ASTRONAUT: ["AS", "TRO", "NAUT"],
  HELICOPTER: ["HEL", "I", "COP", "TER"],
  KANGAROO: ["KAN", "GA", "ROO"],
  ALLIGATOR: ["AL", "LI", "GA", "TOR"],
  VOLCANO: ["VOL", "CA", "NO"],
  TELESCOPE: ["TEL", "E", "SCOPE"],
  // Sight words used in sentences and books
  THE: ["TH", "E"],
  A: ["A"],
  AN: ["A", "N"],
  I: ["I"],
  IS: ["I", "S"],
  IT: ["I", "T"],
  ON: ["O", "N"],
  AT: ["A", "T"],
  LAD: ["L", "A", "D"],
  BAG: ["B", "A", "G"],
  VAN: ["V", "A", "N"],
  NAP: ["N", "A", "P"],
  TAP: ["T", "A", "P"],
  HAD: ["H", "A", "D"],
  TAG: ["T", "A", "G"],
  CAN: ["C", "A", "N"],
  HAS: ["H", "A", "S"],
  IN: ["I", "N"],
  MY: ["M", "Y"],
  WE: ["W", "E"],
  TO: ["T", "O"],
  GO: ["G", "O"],
  SIT: ["S", "I", "T"],
  BIN: ["B", "I", "N"],
  WITH: ["W", "I", "TH"],
  SEE: ["S", "EE"],
  SAT: ["S", "A", "T"],
  HOT: ["H", "O", "T"],
  HOP: ["H", "O", "P"],
  DID: ["D", "I", "D"],
  BIG: ["B", "I", "G"],
  RED: ["R", "E", "D"],
  HEN: ["H", "E", "N"],
  PEN: ["P", "E", "N"],
  BED: ["B", "E", "D"],
  FED: ["F", "E", "D"],
  TEN: ["T", "E", "N"],
  HENS: ["H", "E", "N", "S"],
  BUS: ["B", "U", "S"],
  FLY: ["F", "L", "Y"],
  LIKE: ["L", "I", "KE"],
  LOVE: ["L", "O", "VE"],
  MOM: ["M", "O", "M"],
  BRIGHT: ["BR", "I", "GHT"],
  HAPPY: ["H", "AP", "PY"],
  KID: ["K", "I", "D"],
  PLAYS: ["PL", "A", "YS"],
  HAVE: ["H", "A", "VE"],
  READ: ["R", "EA", "D"],
  MAT: ["M", "A", "T"],
  RUN: ["R", "U", "N"],
  RAN: ["R", "A", "N"],
  FAT: ["F", "A", "T"],
  SAW: ["S", "AW"],
  SWIM: ["SW", "I", "M"],
  HID: ["H", "I", "D"],
  JUMP: ["J", "U", "MP"],
  SCHOOL: ["SCH", "OO", "L"],
};

export function getPhonicsForWord(word: string): string[] {
  const upper = word.toUpperCase().replace(/[^A-Z]/g, "");
  if (!upper) return [];
  if (PHONICS_MAP[upper]) return PHONICS_MAP[upper];
  return upper.split("");
}

export function getPhonicsForSentence(sentence: string): Map<string, string[]> {
  const map = new Map<string, string[]>();
  for (const raw of sentence.split(/\s+/)) {
    const word = raw.replace(/[^A-Za-z]/g, "");
    if (word && !map.has(word.toUpperCase())) {
      map.set(word.toUpperCase(), getPhonicsForWord(word));
    }
  }
  return map;
}
