/** Canonical reading word seed data for levels 1–6 */

export type ReadingWordSeed = { word: string; level: number; imageUrl: string };

const W = "https://upload.wikimedia.org/wikipedia/commons";

export const READING_WORDS_BY_LEVEL: ReadingWordSeed[][] = [
  // Level 1: CVC (3-letter) — 30 words
  [
    { word: "BAT", level: 1, imageUrl: `${W}/7/77/Big-eared-townsend-fledermaus.jpg` },
    { word: "BUG", level: 1, imageUrl: `${W}/e/ed/Insects_-_Neoptera_-_Paleoptera_-_Apterygota.jpg` },
    { word: "BUS", level: 1, imageUrl: `${W}/8/89/London_New_Routemaster.jpg` },
    { word: "CAP", level: 1, imageUrl: `${W}/c/cd/Chapeaux_en_peau_de_castor.jpg` },
    { word: "CAT", level: 1, imageUrl: `${W}/1/15/Cat_August_2010-4.jpg` },
    { word: "CUP", level: 1, imageUrl: `${W}/b/b8/Mug_of_Tea.JPG` },
    { word: "DOG", level: 1, imageUrl: `${W}/7/7a/Huskiesatrest.jpg` },
    { word: "FIN", level: 1, imageUrl: `${W}/7/7f/Balantiocheilos_melanopterus_-_Karlsruhe_Zoo_02_%28cropped%29.jpg` },
    { word: "FIX", level: 1, imageUrl: `${W}/e/e1/Wrench.jpg` },
    { word: "FOX", level: 1, imageUrl: `${W}/d/d2/Portrait_of_a_red_fox_in_Rautas_fj%C3%A4llurskog_%28cropped%29.jpg` },
    { word: "HAT", level: 1, imageUrl: `${W}/c/cd/Chapeaux_en_peau_de_castor.jpg` },
    { word: "HOP", level: 1, imageUrl: `${W}/f/f5/Red-eyed_Leaf_Frog_%2849661076226%29.jpg` },
    { word: "HOT", level: 1, imageUrl: `${W}/8/83/The_Sun_in_white_light.jpg` },
    { word: "LID", level: 1, imageUrl: `${W}/b/b8/Mug_of_Tea.JPG` },
    { word: "LOG", level: 1, imageUrl: `${W}/c/c4/Felling_a_gumtree_c1884-1917_Powerhouse_Museum.jpg` },
    { word: "MAP", level: 1, imageUrl: `${W}/8/89/London_New_Routemaster.jpg` },
    { word: "MAT", level: 1, imageUrl: `${W}/1/15/Cat_August_2010-4.jpg` },
    { word: "MUD", level: 1, imageUrl: `${W}/4/4e/Mud_puddle.jpg` },
    { word: "NET", level: 1, imageUrl: `${W}/7/7f/Balantiocheilos_melanopterus_-_Karlsruhe_Zoo_02_%28cropped%29.jpg` },
    { word: "NUT", level: 1, imageUrl: `${W}/6/6d/Walnuts_-_whole_and_open_with_kernel.jpg` },
    { word: "PAN", level: 1, imageUrl: `${W}/5/5a/Frying_pan.jpg` },
    { word: "PEN", level: 1, imageUrl: `${W}/0/08/Pencils_hb.jpg` },
    { word: "PIG", level: 1, imageUrl: `${W}/3/3e/Pig_farm_Vampula_1.jpg` },
    { word: "RAT", level: 1, imageUrl: `${W}/4/44/Brown_Rat_%28Rattus_norvegicus%29.jpg` },
    { word: "RED", level: 1, imageUrl: `${W}/a/a6/Pink_lady_and_cross_section.jpg` },
    { word: "ROD", level: 1, imageUrl: `${W}/7/7f/Balantiocheilos_melanopterus_-_Karlsruhe_Zoo_02_%28cropped%29.jpg` },
    { word: "RUN", level: 1, imageUrl: `${W}/7/7a/Huskiesatrest.jpg` },
    { word: "SUN", level: 1, imageUrl: `${W}/8/83/The_Sun_in_white_light.jpg` },
    { word: "TUB", level: 1, imageUrl: `${W}/5/5e/Bathtub.jpg` },
    { word: "VAN", level: 1, imageUrl: `${W}/9/9d/Ford_Transit_%28third_generation%29_001.jpg` },
  ],
  // Level 2: 4-letter words — 30 words
  [
    { word: "BALL", level: 2, imageUrl: `${W}/c/ce/Many_balls.jpg` },
    { word: "BANK", level: 2, imageUrl: `${W}/4/4a/Banknotes.jpg` },
    { word: "BASE", level: 2, imageUrl: `${W}/c/ce/Many_balls.jpg` },
    { word: "BEAR", level: 2, imageUrl: `${W}/9/9e/Ours_brun_parcanimalierpyrenees_1.jpg` },
    { word: "BIRD", level: 2, imageUrl: `${W}/b/bf/Bird_Diversity_2013.png` },
    { word: "BOAT", level: 2, imageUrl: `${W}/d/d9/Motorboat_at_Kankaria_lake.JPG` },
    { word: "BOOK", level: 2, imageUrl: `${W}/b/b6/Gutenberg_Bible%2C_Lenox_Copy%2C_New_York_Public_Library%2C_2009._Pic_01.jpg` },
    { word: "CAKE", level: 2, imageUrl: `${W}/0/04/Pound_layer_cake.jpg` },
    { word: "CAMP", level: 2, imageUrl: `${W}/4/4e/Camping_tent_at_Llyn_Cwellyn%2C_Snowdonia%2C_Wales.jpg` },
    { word: "CASH", level: 2, imageUrl: `${W}/4/4a/Banknotes.jpg` },
    { word: "CAVE", level: 2, imageUrl: `${W}/a/a4/Carlsbad_Caverns_National_Park_009.jpg` },
    { word: "COIN", level: 2, imageUrl: `${W}/2/2e/US_Nickel_2013_Rev.png` },
    { word: "DART", level: 2, imageUrl: `${W}/d/d1/Darts_in_a_dartboard.jpg` },
    { word: "DUCK", level: 2, imageUrl: `${W}/b/bf/Bucephala-albeola-010.jpg` },
    { word: "FISH", level: 2, imageUrl: `${W}/7/7f/Balantiocheilos_melanopterus_-_Karlsruhe_Zoo_02_%28cropped%29.jpg` },
    { word: "FROG", level: 2, imageUrl: `${W}/f/f5/Red-eyed_Leaf_Frog_%2849661076226%29.jpg` },
    { word: "HIKE", level: 2, imageUrl: `${W}/e/e7/Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg` },
    { word: "JUMP", level: 2, imageUrl: `${W}/f/f5/Red-eyed_Leaf_Frog_%2849661076226%29.jpg` },
    { word: "MOON", level: 2, imageUrl: `${W}/e/e1/FullMoon2010.jpg` },
    { word: "PARK", level: 2, imageUrl: `${W}/7/7f/Usamljeni_jasen_-_panoramio_%28cropped%29.jpg` },
    { word: "PLAY", level: 2, imageUrl: `${W}/c/ce/Many_balls.jpg` },
    { word: "RIDE", level: 2, imageUrl: `${W}/d/de/Nokota_Horses_cropped.jpg` },
    { word: "ROCK", level: 2, imageUrl: `${W}/e/e7/Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg` },
    { word: "SAVE", level: 2, imageUrl: `${W}/4/4a/Banknotes.jpg` },
    { word: "SHIP", level: 2, imageUrl: `${W}/d/d9/Motorboat_at_Kankaria_lake.JPG` },
    { word: "STAR", level: 2, imageUrl: `${W}/9/9f/Star_cluster_Pismis_24_and_NGC_6357.jpg` },
    { word: "SWIM", level: 2, imageUrl: `${W}/7/7f/Balantiocheilos_melanopterus_-_Karlsruhe_Zoo_02_%28cropped%29.jpg` },
    { word: "TENT", level: 2, imageUrl: `${W}/4/4e/Camping_tent_at_Llyn_Cwellyn%2C_Snowdonia%2C_Wales.jpg` },
    { word: "TOOL", level: 2, imageUrl: `${W}/e/e1/Wrench.jpg` },
    { word: "TREE", level: 2, imageUrl: `${W}/7/7f/Usamljeni_jasen_-_panoramio_%28cropped%29.jpg` },
  ],
  // Level 3: 5-letter words — 30 words
  [
    { word: "ALIEN", level: 3, imageUrl: `${W}/9/91/Bruce_McCandless_II_during_EVA_in_1984.jpg` },
    { word: "APPLE", level: 3, imageUrl: `${W}/a/a6/Pink_lady_and_cross_section.jpg` },
    { word: "BEACH", level: 3, imageUrl: `${W}/6/61/Beach_at_Tulum.jpg` },
    { word: "BOARD", level: 3, imageUrl: `${W}/d/d5/Surfboard_on_the_beach.jpg` },
    { word: "BRUSH", level: 3, imageUrl: `${W}/9/9a/Paintbrush.jpg` },
    { word: "CABIN", level: 3, imageUrl: `${W}/4/4e/Camping_tent_at_Llyn_Cwellyn%2C_Snowdonia%2C_Wales.jpg` },
    { word: "CATCH", level: 3, imageUrl: `${W}/7/7f/Balantiocheilos_melanopterus_-_Karlsruhe_Zoo_02_%28cropped%29.jpg` },
    { word: "CHAIR", level: 3, imageUrl: `${W}/c/c6/Set_of_fourteen_side_chairs_MET_DP110780.jpg` },
    { word: "CLOUD", level: 3, imageUrl: `${W}/1/1d/ISS-40_Thunderheads_near_Borneo.jpg` },
    { word: "DRILL", level: 3, imageUrl: `${W}/e/e1/Wrench.jpg` },
    { word: "FIELD", level: 3, imageUrl: `${W}/7/77/Poa_annua.jpg` },
    { word: "GLOVE", level: 3, imageUrl: `${W}/c/ce/Many_balls.jpg` },
    { word: "GRASS", level: 3, imageUrl: `${W}/7/77/Poa_annua.jpg` },
    { word: "HAPPY", level: 3, imageUrl: `${W}/c/ce/Many_balls.jpg` },
    { word: "HORSE", level: 3, imageUrl: `${W}/d/de/Nokota_Horses_cropped.jpg` },
    { word: "HOUSE", level: 3, imageUrl: `${W}/1/1b/Katsura_Imperial_Villa_in_Spring.jpg` },
    { word: "MAGIC", level: 3, imageUrl: `${W}/4/40/Panor%C3%A1mica_Oto%C3%B1o_Alc%C3%A1zar_de_Segovia.jpg` },
    { word: "MONEY", level: 3, imageUrl: `${W}/4/4a/Banknotes.jpg` },
    { word: "MOUSE", level: 3, imageUrl: `${W}/0/0d/%D0%9C%D1%8B%D1%88%D1%8C_2.jpg` },
    { word: "NIGHT", level: 3, imageUrl: `${W}/e/e1/FullMoon2010.jpg` },
    { word: "OCEAN", level: 3, imageUrl: `${W}/6/61/Beach_at_Tulum.jpg` },
    { word: "RIVER", level: 3, imageUrl: `${W}/3/3f/Lake_mapourika_NZ.jpeg` },
    { word: "SHEEP", level: 3, imageUrl: `${W}/2/2c/Flock_of_sheep.jpg` },
    { word: "SHELL", level: 3, imageUrl: `${W}/6/61/Beach_at_Tulum.jpg` },
    { word: "SMILE", level: 3, imageUrl: `${W}/c/ce/Many_balls.jpg` },
    { word: "SNAKE", level: 3, imageUrl: `${W}/6/60/Trimeresurus_sabahi_fucatus%2C_Banded_pit_viper_-_Takua_Pa_District%2C_Phang-nga_Province_%2846710893582%29.jpg` },
    { word: "THROW", level: 3, imageUrl: `${W}/c/ce/Many_balls.jpg` },
    { word: "TIGER", level: 3, imageUrl: `${W}/b/b0/Bengal_tiger_%28Panthera_tigris_tigris%29_female_3_crop.jpg` },
    { word: "TRAIL", level: 3, imageUrl: `${W}/e/e7/Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg` },
    { word: "WATER", level: 3, imageUrl: `${W}/3/3f/Lake_mapourika_NZ.jpeg` },
  ],
  // Level 4: 6–7 letter words — 30 words
  [
    { word: "ANIMAL", level: 4, imageUrl: `${W}/3/3e/Pig_farm_Vampula_1.jpg` },
    { word: "BATTER", level: 4, imageUrl: `${W}/c/ce/Many_balls.jpg` },
    { word: "BUCKET", level: 4, imageUrl: `${W}/5/5a/Frying_pan.jpg` },
    { word: "CAMERA", level: 4, imageUrl: `${W}/8/82/Camera_icon.svg` },
    { word: "CANYON", level: 4, imageUrl: `${W}/a/a4/Carlsbad_Caverns_National_Park_009.jpg` },
    { word: "CASTLE", level: 4, imageUrl: `${W}/4/40/Panor%C3%A1mica_Oto%C3%B1o_Alc%C3%A1zar_de_Segovia.jpg` },
    { word: "DOCTOR", level: 4, imageUrl: `${W}/8/84/The_Doctor_Luke_Fildes_crop.jpg` },
    { word: "DOLLAR", level: 4, imageUrl: `${W}/4/4a/Banknotes.jpg` },
    { word: "DRAGON", level: 4, imageUrl: `${W}/b/bf/St_Catherine%2C_St_George_and_the_Dragon_%28M%C3%A4staren_fr%C3%A5n_Kappenberg%29_-_Nationalmuseum_-_18337_%28brightened%29%2C_draken.png` },
    { word: "FLIGHT", level: 4, imageUrl: `${W}/3/36/United_Airlines_Boeing_777-200_Meulemans.jpg` },
    { word: "FLOWER", level: 4, imageUrl: `${W}/3/38/Magnolia_grandiflora_-_flower_1.jpg` },
    { word: "FOREST", level: 4, imageUrl: `${W}/7/7f/Usamljeni_jasen_-_panoramio_%28cropped%29.jpg` },
    { word: "GALAXY", level: 4, imageUrl: `${W}/9/9f/Star_cluster_Pismis_24_and_NGC_6357.jpg` },
    { word: "HAMMER", level: 4, imageUrl: `${W}/e/e1/Wrench.jpg` },
    { word: "HIKING", level: 4, imageUrl: `${W}/e/e7/Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg` },
    { word: "ISLAND", level: 4, imageUrl: `${W}/6/61/Beach_at_Tulum.jpg` },
    { word: "LIZARD", level: 4, imageUrl: `${W}/0/0a/Hemidactylus_platyurus_%28Flat-tailed_House_Gecko%29_on_white_background%2C_focus_stacking.jpg` },
    { word: "MONKEY", level: 4, imageUrl: `${W}/d/dc/BrownSpiderMonkey_%28edit2%29.jpg` },
    { word: "NATURE", level: 4, imageUrl: `${W}/7/7f/Usamljeni_jasen_-_panoramio_%28cropped%29.jpg` },
    { word: "ORANGE", level: 4, imageUrl: `${W}/e/e3/Oranges_-_whole-halved-segment.jpg` },
    { word: "PARADE", level: 4, imageUrl: `${W}/c/ce/Many_balls.jpg` },
    { word: "PENCIL", level: 4, imageUrl: `${W}/0/08/Pencils_hb.jpg` },
    { word: "PITCHER", level: 4, imageUrl: `${W}/c/ce/Many_balls.jpg` },
    { word: "PLANET", level: 4, imageUrl: `${W}/9/9f/Star_cluster_Pismis_24_and_NGC_6357.jpg` },
    { word: "RABBIT", level: 4, imageUrl: `${W}/1/1f/Oryctolagus_cuniculus_Rcdo.jpg` },
    { word: "ROCKET", level: 4, imageUrl: `${W}/9/9a/Soyuz_TMA-9_launch.jpg` },
    { word: "SPIDER", level: 4, imageUrl: `${W}/2/26/Araneae3.jpg` },
    { word: "TICKET", level: 4, imageUrl: `${W}/c/ce/Many_balls.jpg` },
    { word: "TURTLE", level: 4, imageUrl: `${W}/2/21/Turtle_diversity.jpg` },
    { word: "WALLEYE", level: 4, imageUrl: `${W}/7/7f/Balantiocheilos_melanopterus_-_Karlsruhe_Zoo_02_%28cropped%29.jpg` },
  ],
  // Level 5: 8+ letter words — 30 words
  [
    { word: "ADVENTURE", level: 5, imageUrl: `${W}/e/e7/Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg` },
    { word: "AIRPLANE", level: 5, imageUrl: `${W}/3/36/United_Airlines_Boeing_777-200_Meulemans.jpg` },
    { word: "ALLIGATOR", level: 5, imageUrl: `${W}/4/4a/Chinese%2Bamerican_alligators.png` },
    { word: "ASTRONAUT", level: 5, imageUrl: `${W}/9/91/Bruce_McCandless_II_during_EVA_in_1984.jpg` },
    { word: "BACKPACK", level: 5, imageUrl: `${W}/e/e7/Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg` },
    { word: "BASEBALL", level: 5, imageUrl: `${W}/c/ce/Many_balls.jpg` },
    { word: "BLEACHERS", level: 5, imageUrl: `${W}/c/ce/Many_balls.jpg` },
    { word: "BUTTERFLY", level: 5, imageUrl: `${W}/3/3d/Fesoj_-_Papilio_machaon_%28by%29.jpg` },
    { word: "CAMPFIRE", level: 5, imageUrl: `${W}/4/4e/Camping_tent_at_Llyn_Cwellyn%2C_Snowdonia%2C_Wales.jpg` },
    { word: "CAMPGROUND", level: 5, imageUrl: `${W}/4/4e/Camping_tent_at_Llyn_Cwellyn%2C_Snowdonia%2C_Wales.jpg` },
    { word: "DINOSAUR", level: 5, imageUrl: `${W}/c/c5/Sinosauropteryxfossil.jpg` },
    { word: "ELEPHANT", level: 5, imageUrl: `${W}/3/37/African_Bush_Elephant.jpg` },
    { word: "HELICOPTER", level: 5, imageUrl: `${W}/7/78/LAPD_Bell_206_Jetranger.jpg` },
    { word: "KANGAROO", level: 5, imageUrl: `${W}/d/df/Forester_kangaroo_%28Macropus_giganteus_tasmaniensis%29_juvenile_hopping_Esk_Valley.jpg` },
    { word: "MINNESOTA", level: 5, imageUrl: `${W}/3/3f/Lake_mapourika_NZ.jpeg` },
    { word: "MOSQUITO", level: 5, imageUrl: `${W}/e/ed/Insects_-_Neoptera_-_Paleoptera_-_Apterygota.jpg` },
    { word: "MOUNTAIN", level: 5, imageUrl: `${W}/e/e7/Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg` },
    { word: "PRINCESS", level: 5, imageUrl: `${W}/4/40/Panor%C3%A1mica_Oto%C3%B1o_Alc%C3%A1zar_de_Segovia.jpg` },
    { word: "ROADTRIP", level: 5, imageUrl: `${W}/9/9d/Ford_Transit_%28third_generation%29_001.jpg` },
    { word: "SPACESHIP", level: 5, imageUrl: `${W}/9/9a/Soyuz_TMA-9_launch.jpg` },
    { word: "SUNGLASSES", level: 5, imageUrl: `${W}/8/83/The_Sun_in_white_light.jpg` },
    { word: "SUNSHINE", level: 5, imageUrl: `${W}/8/83/The_Sun_in_white_light.jpg` },
    { word: "TELESCOPE", level: 5, imageUrl: `${W}/a/ac/100inchHooker.jpg` },
    { word: "THEMEPARK", level: 5, imageUrl: `${W}/c/ce/Many_balls.jpg` },
    { word: "UMBRELLA", level: 5, imageUrl: `${W}/8/87/M0354_000727-005_1.jpg` },
    { word: "VACATION", level: 5, imageUrl: `${W}/6/61/Beach_at_Tulum.jpg` },
    { word: "VOLCANO", level: 5, imageUrl: `${W}/4/48/Augustine_volcano_Jan_24_2006_-_Cyrus_Read.jpg` },
    { word: "WATERFALL", level: 5, imageUrl: `${W}/3/3f/Lake_mapourika_NZ.jpeg` },
    { word: "WILDERNESS", level: 5, imageUrl: `${W}/7/7f/Usamljeni_jasen_-_panoramio_%28cropped%29.jpg` },
    { word: "WOODLAND", level: 5, imageUrl: `${W}/7/7f/Usamljeni_jasen_-_panoramio_%28cropped%29.jpg` },
  ],
];

export const READING_SENTENCES_LEVEL_6: ReadingWordSeed[] = [
  { word: "THE CAT SAT ON THE MAT", level: 6, imageUrl: `${W}/1/15/Cat_August_2010-4.jpg` },
  { word: "I SEE A BIG RED BUG", level: 6, imageUrl: `${W}/e/ed/Insects_-_Neoptera_-_Paleoptera_-_Apterygota.jpg` },
  { word: "THE SUN IS HOT TODAY", level: 6, imageUrl: `${W}/8/83/The_Sun_in_white_light.jpg` },
  { word: "I HAVE A NET FOR FISH", level: 6, imageUrl: `${W}/7/7f/Balantiocheilos_melanopterus_-_Karlsruhe_Zoo_02_%28cropped%29.jpg` },
  { word: "WE GO TO CAMP IN THE WOODS", level: 6, imageUrl: `${W}/4/4e/Camping_tent_at_Llyn_Cwellyn%2C_Snowdonia%2C_Wales.jpg` },
  { word: "I SEE THE STARS AT NIGHT", level: 6, imageUrl: `${W}/9/9f/Star_cluster_Pismis_24_and_NGC_6357.jpg` },
  { word: "HIT THE BALL WITH THE BAT", level: 6, imageUrl: `${W}/c/ce/Many_balls.jpg` },
  { word: "WE RUN FAST ON THE GRASS", level: 6, imageUrl: `${W}/7/77/Poa_annua.jpg` },
  { word: "THE TENT IS BIG AND GREEN", level: 6, imageUrl: `${W}/4/4e/Camping_tent_at_Llyn_Cwellyn%2C_Snowdonia%2C_Wales.jpg` },
  { word: "I LIKE TO PLAY IN THE SAND", level: 6, imageUrl: `${W}/6/61/Beach_at_Tulum.jpg` },
  { word: "LOOK AT THE MOON IN THE SKY", level: 6, imageUrl: `${W}/e/e1/FullMoon2010.jpg` },
  { word: "HE WILL JUMP OVER THE LOG", level: 6, imageUrl: `${W}/c/c4/Felling_a_gumtree_c1884-1917_Powerhouse_Museum.jpg` },
  { word: "IT IS A SHIP ON THE WATER", level: 6, imageUrl: `${W}/d/d9/Motorboat_at_Kankaria_lake.JPG` },
  { word: "SHE IS HAPPY TO RIDE THE BUS", level: 6, imageUrl: `${W}/8/89/London_New_Routemaster.jpg` },
  { word: "WE HIKE THE HILL TO THE CAVE", level: 6, imageUrl: `${W}/a/a4/Carlsbad_Caverns_National_Park_009.jpg` },
  { word: "THE BEAR IS BIG AND BROWN", level: 6, imageUrl: `${W}/9/9e/Ours_brun_parcanimalierpyrenees_1.jpg` },
  { word: "I CAN SWIM FAST IN THE LAKE", level: 6, imageUrl: `${W}/3/3f/Lake_mapourika_NZ.jpeg` },
  { word: "WE FLY IN THE SKY TO THE SUN", level: 6, imageUrl: `${W}/3/36/United_Airlines_Boeing_777-200_Meulemans.jpg` },
  { word: "I HAVE A TICKET FOR THE RIDE", level: 6, imageUrl: `${W}/c/ce/Many_balls.jpg` },
  { word: "THE MAGIC IS REAL IN THE CASTLE", level: 6, imageUrl: `${W}/4/40/Panor%C3%A1mica_Oto%C3%B1o_Alc%C3%A1zar_de_Segovia.jpg` },
  { word: "SHE CAN THROW IT TO THE BASE", level: 6, imageUrl: `${W}/c/ce/Many_balls.jpg` },
  { word: "WE SAVE THE COIN IN THE BANK", level: 6, imageUrl: `${W}/4/4a/Banknotes.jpg` },
  { word: "I USE THE TOOL TO FIX IT", level: 6, imageUrl: `${W}/e/e1/Wrench.jpg` },
  { word: "WE WILL CATCH A FISH TODAY", level: 6, imageUrl: `${W}/7/7f/Balantiocheilos_melanopterus_-_Karlsruhe_Zoo_02_%28cropped%29.jpg` },
];

/** Flat list of all canonical reading word seeds (levels 1–6) */
export const ALL_READING_WORD_SEEDS: ReadingWordSeed[] = [
  ...READING_WORDS_BY_LEVEL.flat(),
  ...READING_SENTENCES_LEVEL_6,
];

/** Marker word used to detect whether expanded vocabulary migration has run */
export const EXPANDED_VOCAB_MARKER = "VAN";
